export const GET_TOPICS_EVENT = 'GET_TOPICS_EVENT';
export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
export const GET_TOPICS_FAILED = 'GET_TOPICS_FAILED';

export const CREATE_TOPIC_EVENT = 'CREATE_TOPIC_EVENT';
export const CREATE_TOPIC_SUCCESS = 'CREATE_TOPIC_SUCCESS';
export const CREATE_TOPIC_FAILED = 'CREATE_TOPIC_FAILED';

export const UPVOTE_TOPIC_EVENT = 'UPVOTE_TOPIC_EVENT';
export const UPVOTE_TOPIC_SUCCESS = 'UPVOTE_TOPIC_SUCCESS';
export const UPVOTE_TOPIC_FAILED = 'UPVOTE_TOPIC_FAILED';

export const DOWNVOTE_TOPIC_EVENT = 'DOWNVOTE_TOPIC_EVENT';
export const DOWNVOTE_TOPIC_SUCCESS = 'DOWNVOTE_TOPIC_SUCCESS';
export const DOWNVOTE_TOPIC_FAILED = 'DOWNVOTE_TOPIC_FAILED';